# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='multipleChoiceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('questionNo', models.IntegerField(null=True)),
                ('question', models.CharField(max_length=2000)),
                ('optionOne', models.CharField(max_length=1000)),
                ('optionTwo', models.CharField(max_length=1000)),
                ('optionThree', models.CharField(max_length=1000)),
                ('optionFour', models.CharField(max_length=1000)),
                ('optionOneAns', models.BooleanField()),
                ('optionTwoAns', models.BooleanField()),
                ('optionThreeAns', models.BooleanField()),
                ('optionFourAns', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='textQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('questionNo', models.IntegerField(null=True)),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
    ]
