# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180918_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNo', models.IntegerField(null=True)),
                ('question', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('optionOne', models.CharField(max_length=1000)),
                ('optionTwo', models.CharField(max_length=1000)),
                ('optionThree', models.CharField(max_length=1000)),
                ('optionFour', models.CharField(max_length=1000)),
                ('optionOneAns', models.BooleanField()),
                ('optionTwoAns', models.BooleanField()),
                ('optionThreeAns', models.BooleanField()),
                ('optionFourAns', models.BooleanField()),
            ],
        ),
    ]
