# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_imagequestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestions',
            name='answer',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
