# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180918_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestions',
            name='answer',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
