# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180918_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='objResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('marks', models.IntegerField(null=True)),
            ],
        ),
    ]
