# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_objresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='textAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('qnOneAns', models.CharField(max_length=2000)),
                ('qnTwoAns', models.CharField(max_length=2000)),
                ('qnThreeAns', models.CharField(max_length=2000)),
                ('qnFourAns', models.CharField(max_length=2000)),
                ('qnFiveAns', models.CharField(max_length=2000)),
                ('qnSixAns', models.CharField(max_length=2000)),
                ('marks', models.IntegerField(null=True)),
            ],
        ),
    ]
